"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TimbreFiscalDigital = exports.ServiciosPlataformasTecnologicas = exports.Servicio = exports.Intereses = exports.ImpuestosTrasladadosdelServicio = exports.ContribucionGubernamental = exports.ComisionDelServicio = exports.Complemento = void 0;
const Complemento_1 = require("./Complemento");
Object.defineProperty(exports, "Complemento", { enumerable: true, get: function () { return Complemento_1.Complemento; } });
const ComisionDelServicio_1 = require("./ComisionDelServicio");
Object.defineProperty(exports, "ComisionDelServicio", { enumerable: true, get: function () { return ComisionDelServicio_1.ComisionDelServicio; } });
const ContribucionGubernamental_1 = require("./ContribucionGubernamental");
Object.defineProperty(exports, "ContribucionGubernamental", { enumerable: true, get: function () { return ContribucionGubernamental_1.ContribucionGubernamental; } });
const ImpuestosTrasladadosdelServicio_1 = require("./ImpuestosTrasladadosdelServicio");
Object.defineProperty(exports, "ImpuestosTrasladadosdelServicio", { enumerable: true, get: function () { return ImpuestosTrasladadosdelServicio_1.ImpuestosTrasladadosdelServicio; } });
const Intereses_1 = require("./Intereses");
Object.defineProperty(exports, "Intereses", { enumerable: true, get: function () { return Intereses_1.Intereses; } });
const Servicio_1 = require("./Servicio");
Object.defineProperty(exports, "Servicio", { enumerable: true, get: function () { return Servicio_1.Servicio; } });
const ServiciosPlataformasTecnologicas_1 = require("./ServiciosPlataformasTecnologicas");
Object.defineProperty(exports, "ServiciosPlataformasTecnologicas", { enumerable: true, get: function () { return ServiciosPlataformasTecnologicas_1.ServiciosPlataformasTecnologicas; } });
const TimbreFiscalDigital_1 = require("./TimbreFiscalDigital");
Object.defineProperty(exports, "TimbreFiscalDigital", { enumerable: true, get: function () { return TimbreFiscalDigital_1.TimbreFiscalDigital; } });
